[variables]
PLAYWRIGHT_BROWSERS_PATH = "0"
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_22", "pnpm_9", "chromium"]

[phases.install]
cmds = ["pnpm install"]

[phases.build]
cmds = ["pnpm run build", "npx playwright install --only-shell chromium"]

[start]
cmd = "NODE_ENV=production node --max-old-space-size=160 dist/server.cjs"
