import { InvestigationRecord } from '../../types/investigation';

/**
 * Generates an authoritative, structured Markdown document from an InvestigationRecord
 */
export function generateResearchFindingsMarkdown(investigation: InvestigationRecord): string {
  const dateStr = new Date(investigation.createdAt).toISOString().split('T')[0];
  const title = investigation.title || 'Probe Research Investigation';
  const query = investigation.query || title;

  // Aggregate stats
  const assumptions = investigation.assumptions || [];
  const supportedCount = assumptions.filter((a) => a.status === 'SUPPORTED').length;
  const challengedCount = assumptions.filter((a) => a.status === 'CHALLENGED').length;
  const unknownCount = assumptions.filter((a) => a.status === 'UNKNOWN').length;

  const evidence = investigation.evidence || [];
  const contradictions = investigation.contradictions || [];
  const experiments = investigation.experiments || [];
  const academicResearch = investigation.academicResearch || {};

  const scholarPapers = Object.values(academicResearch).flatMap((ar) => ar.papers || []);

  let md = `# Probe Research Findings: ${title}\n\n`;
  md += `> **Query / Idea:** "${query}"  \n`;
  md += `> **Investigation ID:** \`${investigation.id}\`  \n`;
  md += `> **Date:** ${dateStr}  \n`;
  md += `> **Generated by:** Probe Empirical Research Platform  \n`;
  md += `> **Status:** ${investigation.status.toUpperCase()} | Stage: \`${investigation.currentStage}\`\n\n`;
  md += `---\n\n`;

  // 1. Executive Summary
  md += `## 1. Executive Summary\n\n`;
  if (investigation.documentContext?.problem) {
    md += `**Document Problem Context:** ${investigation.documentContext.problem}\n\n`;
  }
  md += `Probe conducted a multi-source investigation across open web communities, developer forums, industry benchmarks, and peer-reviewed literature. `;
  md += `Across **${assumptions.length} core hypotheses**, **${supportedCount} are supported**, **${challengedCount} are challenged by empirical friction**, and **${unknownCount} remain unverified unknowns** requiring experimental validation.\n\n`;

  if (contradictions.length > 0) {
    const topRisk = contradictions[0];
    md += `**Primary Friction / Risk:** ${topRisk.title} — *"${topRisk.quote}"* (Severity: ${topRisk.severity}). Countermeasure: ${topRisk.counterMeasure}\n\n`;
  }

  md += `---\n\n`;

  // 2. Hypotheses & Assumptions Matrix
  md += `## 2. Hypotheses & Assumptions Matrix\n\n`;
  md += `| ID | Assumption Statement | Empirical Status | Strength | Citation / Source |\n`;
  md += `|---|---|---|---|---|\n`;
  if (assumptions.length === 0) {
    md += `| \`A-001\` | Initial product viability and user demand | **[EARLY SIGNAL]** | Moderate | Web Synthesis |\n`;
  } else {
    for (const a of assumptions) {
      const statusBadge = `**[${a.status}]**`;
      const strength = a.strengthScore ? `${a.strengthScore}/100` : 'Evaluated';
      const source = a.sources && a.sources[0] ? a.sources[0].replace(/[|\n]/g, ' ') : 'Multi-source consensus';
      md += `| \`${a.id}\` | ${a.text.replace(/[|\n]/g, ' ')} | ${statusBadge} | ${strength} | ${source} |\n`;
    }
  }
  md += `\n---\n\n`;

  // 3. Verified Multi-Source Evidence
  md += `## 3. Verified Multi-Source Evidence\n\n`;
  if (evidence.length === 0) {
    md += `*No external evidence items linked yet.*\n\n`;
  } else {
    evidence.forEach((ev, idx) => {
      md += `### EVID-${String(idx + 1).padStart(3, '0')}: ${ev.sourceName} (${ev.relationship})\n`;
      md += `- **Source Domain:** \`${ev.domain || 'External Evidence'}\`\n`;
      if (ev.url) md += `- **Link:** [${ev.url}](${ev.url})\n`;
      md += `- **Relevance Score:** ${ev.relevanceScore}/100 | **Quality:** ${ev.qualityScore}/100\n`;
      md += `- **Verbatim Excerpt:**\n`;
      md += `  > "${ev.excerpt.replace(/\n+/g, ' ')}"\n`;
      if (ev.explanation) {
        md += `- **Analysis:** ${ev.explanation}\n`;
      }
      md += `\n`;
    });
  }
  md += `---\n\n`;

  // 4. Academic Literature Consensus (ScholarXIV)
  md += `## 4. Academic Literature & Empirical Consensus\n\n`;
  if (scholarPapers.length === 0) {
    md += `*No peer-reviewed papers retrieved for this investigation.*\n\n`;
  } else {
    scholarPapers.forEach((paper, pIdx) => {
      md += `### Paper ${pIdx + 1}: ${paper.title}\n`;
      md += `- **Authors:** ${paper.authors}${paper.year ? ` (${paper.year})` : ''}\n`;
      md += `- **Stance:** **${paper.stance}** (${paper.stanceLabel})\n`;
      if (paper.url) md += `- **Paper URL:** [${paper.url}](${paper.url})\n`;
      md += `- **Abstract Finding:** ${paper.shortFinding || paper.abstract.slice(0, 240)}...\n\n`;
    });
  }
  md += `---\n\n`;

  // 5. Fatal Contradictions & Friction Signals
  md += `## 5. Contradictions & Customer Friction Signals\n\n`;
  if (contradictions.length === 0) {
    md += `*No severe contradictions flagged during this research run.*\n\n`;
  } else {
    contradictions.forEach((c, cIdx) => {
      md += `### Risk ${cIdx + 1}: ${c.title} [Severity: ${c.severity}]\n`;
      md += `- **Source:** ${c.source}\n`;
      md += `- **Customer Quote / Observation:** *"${c.quote}"*\n`;
      md += `- **Countermeasure Strategy:** ${c.counterMeasure}\n\n`;
    });
  }
  md += `---\n\n`;

  // 6. Validation Experiments & Smoke Tests
  md += `## 6. Recommended Validation Experiments\n\n`;
  if (experiments.length === 0) {
    md += `*Recommended: Deploy a 48-hour smoke test or clickable prototype to test unverified assumptions.*\n\n`;
  } else {
    experiments.forEach((exp, eIdx) => {
      md += `### Experiment ${eIdx + 1}: ${exp.title} (${exp.status.toUpperCase()})\n`;
      md += `- **Test Type:** \`${exp.testType}\` | **Duration:** ${exp.duration}\n`;
      md += `- **Hypothesis:** ${exp.hypothesis}\n`;
      md += `- **Target Audience:** ${exp.targetAudience}\n`;
      md += `- **Success Metric:** ${exp.successMetric}\n\n`;
    });
  }
  md += `---\n\n`;

  // 7. Traceability & Next Steps
  md += `## 7. Next Steps & PRD Translation\n\n`;
  md += `1. **Review High-Risk Contradictions:** Address customer objections before writing software.\n`;
  md += `2. **Execute Validation Experiment:** Complete the smoke test to turn assumptions into validated facts.\n`;
  md += `3. **Generate PRD:** Use Probe's Research-to-PRD generator to produce an implementation-ready build specification.\n\n`;
  md += `---\n`;
  md += `*Document generated by Probe Research Platform (https://probe.dev)*\n`;

  return md;
}

/**
 * Triggers a browser download of a UTF-8 text/markdown file
 */
export function downloadMarkdownFile(content: string, filename: string): void {
  const safeFilename = filename.endsWith('.md') ? filename : `${filename}.md`;
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = safeFilename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Opens a dedicated printable window with clean typography for saving as PDF
 */
export function printOrDownloadAsPdf(title: string, markdownContent: string): void {
  // Simple markdown to HTML conversion for high-quality printing
  const htmlContent = markdownToPrintableHtml(title, markdownContent);
  const printWindow = window.open('', '_blank');

  if (!printWindow) {
    // If popups are blocked, fallback to iframe print
    printViaHiddenIframe(htmlContent);
    return;
  }

  printWindow.document.open();
  printWindow.document.write(htmlContent);
  printWindow.document.close();

  printWindow.onload = () => {
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
    }, 250);
  };
}

/**
 * Fallback print mechanism using hidden iframe
 */
function printViaHiddenIframe(htmlContent: string): void {
  const iframe = document.createElement('iframe');
  iframe.style.position = 'fixed';
  iframe.style.right = '0';
  iframe.style.bottom = '0';
  iframe.style.width = '0';
  iframe.style.height = '0';
  iframe.style.border = '0';
  document.body.appendChild(iframe);

  const doc = iframe.contentWindow?.document;
  if (!doc) return;

  doc.open();
  doc.write(htmlContent);
  doc.close();

  iframe.contentWindow?.focus();
  setTimeout(() => {
    iframe.contentWindow?.print();
    setTimeout(() => {
      document.body.removeChild(iframe);
    }, 2000);
  }, 300);
}

/**
 * Converts markdown string to clean, printable HTML with print stylesheets
 */
export function markdownToPrintableHtml(docTitle: string, markdown: string): string {
  // Lightweight markdown to HTML conversion
  const lines = markdown.split('\n');
  let inTable = false;
  let inCode = false;
  let html = '';

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    if (line.startsWith('```')) {
      if (inCode) {
        html += '</pre>\n';
        inCode = false;
      } else {
        html += '<pre><code>';
        inCode = true;
      }
      continue;
    }

    if (inCode) {
      html += escapeHtml(line) + '\n';
      continue;
    }

    if (line.startsWith('|') && line.endsWith('|')) {
      if (!inTable) {
        html += '<table class="doc-table">\n';
        inTable = true;
      }
      // Separator row
      if (line.includes('---')) continue;

      const cells = line
        .split('|')
        .slice(1, -1)
        .map((c) => c.trim());
      const isHeader = i > 0 && lines[i + 1]?.includes('---');
      const tag = isHeader ? 'th' : 'td';

      html += '  <tr>' + cells.map((c) => `<${tag}>${formatInline(c)}</${tag}>`).join('') + '</tr>\n';
      continue;
    } else if (inTable) {
      html += '</table>\n';
      inTable = false;
    }

    if (line.startsWith('# ')) {
      html += `<h1>${formatInline(line.slice(2))}</h1>\n`;
    } else if (line.startsWith('## ')) {
      html += `<h2>${formatInline(line.slice(3))}</h2>\n`;
    } else if (line.startsWith('### ')) {
      html += `<h3>${formatInline(line.slice(4))}</h3>\n`;
    } else if (line.startsWith('#### ')) {
      html += `<h4>${formatInline(line.slice(5))}</h4>\n`;
    } else if (line.startsWith('> ')) {
      html += `<blockquote>${formatInline(line.slice(2))}</blockquote>\n`;
    } else if (line.startsWith('- ') || line.startsWith('* ')) {
      html += `<li>${formatInline(line.slice(2))}</li>\n`;
    } else if (line.match(/^\d+\.\s/)) {
      html += `<li>${formatInline(line.replace(/^\d+\.\s/, ''))}</li>\n`;
    } else if (line.trim() === '---') {
      html += '<hr />\n';
    } else if (line.trim()) {
      html += `<p>${formatInline(line)}</p>\n`;
    }
  }

  if (inTable) html += '</table>\n';
  if (inCode) html += '</pre>\n';

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${escapeHtml(docTitle)}</title>
  <style>
    @media print {
      body {
        margin: 0;
        padding: 20mm 15mm;
        font-size: 10.5pt;
        line-height: 1.5;
        color: #0A0D14;
      }
      .no-print { display: none !important; }
      h1, h2, h3 { page-break-after: avoid; }
      table, pre, blockquote { page-break-inside: avoid; }
      a { color: #0A0D14; text-decoration: underline; }
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
      max-width: 860px;
      margin: 40px auto;
      padding: 0 24px;
      color: #0A0D14;
      line-height: 1.6;
    }
    .print-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 24px;
      padding-bottom: 16px;
      border-bottom: 2px solid #E5E7EB;
    }
    .brand-mark {
      font-weight: 900;
      font-size: 18px;
      letter-spacing: -0.5px;
      color: #0A0D14;
    }
    .btn-print {
      background: #0A0D14;
      color: #FFFFFF;
      border: 0;
      padding: 8px 16px;
      border-radius: 8px;
      font-size: 12px;
      font-weight: 600;
      cursor: pointer;
    }
    h1 { font-size: 24pt; font-weight: 800; letter-spacing: -0.5px; margin-top: 18px; margin-bottom: 12px; }
    h2 { font-size: 16pt; font-weight: 700; border-bottom: 1px solid #E5E7EB; padding-bottom: 6px; margin-top: 24px; }
    h3 { font-size: 13pt; font-weight: 600; margin-top: 18px; margin-bottom: 6px; }
    h4 { font-size: 11pt; font-weight: 600; margin-top: 14px; }
    p { margin: 8px 0; }
    blockquote {
      margin: 12px 0;
      padding: 8px 16px;
      background: #F8FAFC;
      border-left: 3px solid #0091FF;
      color: #334155;
      font-size: 10.5pt;
    }
    .doc-table {
      width: 100%;
      border-collapse: collapse;
      margin: 16px 0;
      font-size: 9.5pt;
    }
    .doc-table th, .doc-table td {
      border: 1px solid #E2E8F0;
      padding: 7px 10px;
      text-align: left;
    }
    .doc-table th {
      background: #F8FAFC;
      font-weight: 700;
      color: #0F172A;
    }
    pre {
      background: #0F172A;
      color: #F8FAFC;
      padding: 14px;
      border-radius: 8px;
      overflow-x: auto;
      font-size: 9pt;
      font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
    }
    code {
      font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
      font-size: 9pt;
      background: #F1F5F9;
      padding: 2px 5px;
      border-radius: 4px;
      color: #0F172A;
    }
    li { margin: 4px 0; }
    hr { border: 0; border-top: 1px solid #E2E8F0; margin: 24px 0; }
    .badge {
      display: inline-block;
      padding: 2px 6px;
      border-radius: 4px;
      font-size: 8.5pt;
      font-weight: 700;
      font-family: ui-monospace, monospace;
    }
  </style>
</head>
<body>
  <div class="print-header no-print">
    <div class="brand-mark">PROBE · Research Findings Document</div>
    <button class="btn-print" onclick="window.print()">Print / Save as PDF</button>
  </div>
  ${html}
</body>
</html>`;
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function formatInline(str: string): string {
  return str
    .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
    .replace(/\*([^*]+)\*/g, '<em>$1</em>')
    .replace(/`([^`]+)`/g, '<code>$1</code>')
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2" target="_blank" rel="noopener">$1</a>');
}
